### ISSUE TITLE
Document optimal setting for ui.key.accelKey

### ISSUE THREAD

**Issue by sdelafond** [jumper047/tridactyl_emacs_config#1]
`91` works fine here, but it'd probably be good to be a bit more explicit about what the various settings listed on the reddit page imply.

Awesome work on that initial set of keybindings, BTW :)

**Comment by jumper047** [comment]
Thx, you're right - there were too much links in readme. Added more detailed instructions.

**Comment by jumper047** [comment]
> Awesome work on that initial set of keybindings, BTW :)

Thank you ^_^
