### ISSUE TITLE
Native messenger is optional

### ISSUE THREAD

**Issue by bovine3dom** [jumper047/tridactyl_emacs_config#3]
`:source --url https://raw.githubusercontent.com/jumper047/tridactyl_emacs_config/main/emacs_bindings` (should) work fine with no need for the native messenger : )

**Comment by jumper047** [comment]
Actually I knew about it, but first time I found no reason not to use config file:). But after your issue I found one - update bindings with alias. Readme and bindings updated!

P.S. Tridactyl is awesome - it feels like old good XUL extensions! Thank you!:)
