### ISSUE TITLE
C-g bind makes escapehatch worse

### ISSUE THREAD

**Issue by bovine3dom** [jumper047/tridactyl_emacs_config#6]
https://github.com/jumper047/tridactyl_emacs_config/blob/d1475505eead8e5bc70526190f3ff72c6d6ebbc2/emacs_bindings#L9

As soon as you use `composite` Firefox doesn't believe that a user truly wanted anything useful to happen and we have to fall back to a worse version of the escapehatch that can't get focus back from the address bar: https://github.com/tridactyl/tridactyl/blob/935fa10efe03d473e9be6d173cb2cf352ad1534e/src/background/user_actions.ts#L14

If you bind only to escapehatch instead we have a special case that means Firefox will execute exactly what you asked: https://github.com/tridactyl/tridactyl/blob/935fa10efe03d473e9be6d173cb2cf352ad1534e/src/background/commands.ts#L13

```
bind --mode=browser <C-g> escapehatch
```

Obviously you'd lose the clear searchlight bit.

**Comment by jumper047** [comment]
Thank you, it definitely works better this way. Still embarrassed a little with persistent search highlight, but seems like it is lesser evil. Missed emacs-ish "exit-command-mode-hook":).

**Comment by bovine3dom** [comment]
I suppose we could allow binding to multiple things at once, e.g. `bind --mode=browser ["escapehatch", "clearsearchhighlight"]`.

I'm not sure it's worth the effort since outside of "user actions" (which at the moment is just `escapehatch`) `composite` with semi-colons has the same effect.

**Comment by jumper047** [comment]
Or maybe add timeout to highlighting. Is it possible?

**Comment by bovine3dom** [comment]
Sure: https://github.com/tridactyl/tridactyl/pull/3854

**Comment by jumper047** [comment]
Wow, it was quick!

**Comment by bovine3dom** [comment]
One line of code in an hour, it's a productivity rate that those bloated legacy FAANG corporations can only dream of ; )
